name: ts-interpretability-benchmark

channels:
  - pytorch
  - conda-forge

dependencies:
  - python>=3.6.3
  - torchvision
  - pytorch
  - matplotlib
  - pandas
  - scikit-learn
  - symengine
  - imbalanced-learn
  - pip
  - pip:
      - timesynth
      - captum
