name: ts-interpretability-benchmark

channels:
  - pytorch
  - conda-forge
  - defaults

dependencies:
  - python>=3.6.3
  - torchvision
  - matplotlib
  - pandas
  - scikit-learn
  - symengine
  - pytorch
  - numpy
  - pip
  - pip:
      - timesynth
      - captum
